- name: Install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Intall package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "mysql", state: "absent"}
    - { name: "zip", state: "present"}  
    - { name: "nginx", state: "present"} 

    