- name: Install packages
  hosts: local
  connection: local
  tasks:
  - name: Intall package
    ansible.builtin.package:
      name: "Installing {{ item }}"
      state: present
    loop:
    - nginx
    - zip
    - mysql  