- name: Ansible shell module
  hosts:  local
  connection: local
  tasks:
  - name: Command Module Test
    ansible.builtin.shell: cat /etc/passwd |grep -i  root
    register: users_output

  - name: Print output
    ansible.builtin.debug:
      msg: "{{ users_output }}"


  - name: Command Module Test
    ansible.builtin.shell: ls -ltr > files.txt
    register: files_output

  - name: Print output
    ansible.builtin.debug:
      msg: "{{ files_output }}"