- name : Number of Ansible lessons greater than 5
  hosts: local
  connection: local
  vars:
    NUMBER_LESSONS : 7
  tasks:
  - name: Number of Ansible lessons greater than 5
    ansible.builtin.debug:
      msg: "Yes, greater than 5"
    when: NUMBER_LESSONS > 7






 