- name: check a number less than 10 or not
  hosts: local
  connection: local
  vars:
   NUMBER_OF_SESSIONS: 7
  tasks:
  - name: is ansible more than 5 sessions
    ansible.builtin.debug:
    msg: "Yes,Number of ansible lessons ,More than 5"
  when: NUMBER_OF_SESSIONS > 5

